
title: Gardner Self Publication Platform
email: Perseidsadmin@gmail.com
description: The Gardner platform is built so that any Perseids user can host their own publications on their own blog or website, easily and quickly.
baseurl: "/GardnerPrototype"
url: "https://tdbuck.github.io/GardnerPrototype" 
twitter_username: PerseidsProject
github_username:  TDBuck
syntax-highlighting: 
  enabled : true
  highlighter: rouge
collections:
  tbpages:
    output: true
    permalink: :title.html

markdown: kramdown

gems: 
  - jekyll-feed
  - jekyll-coffeescript

gems: [ jekyll-watch, jekyll-assets]
exclude:
  - Gemfile
  - Gemfile.lock
assets:
  assets:
    - "*.json"
    - "*.js"
    - "*.css"
    - "*.png"
    - "*.ttf"
    - "*.svg"
    - "*.eot"
    - "*.otf"
    - "*.woff"
  sources:
    - _assets/arethusa
